### ISSUE TITLE
Crash on Dedicated Server

### ISSUE THREAD

**Issue by Liamgrayskull** [JSJBDEV/Almanac#1]
Doesn't function in a dedicated server environment, incorrect environment error
https://mclo.gs/kKS1ZPw

(love the mod!)

**Comment by Burgersim** [comment]
Aww came here to report the same thing, I so wanted to try this on my server, bc I think sharing via an in-game book is so much more "intuitive"/immersive. But alas, it just crashed my 1.20.1 dedicated server ^^*

https://pastebin.com/i7sryFWF

**Comment by JSJBDEV** [comment]
Yeah I remember seeing this notification and then apparently I didn't act on it

**Comment by JSJBDEV** [comment]
I only now notice because of @Liamgrayskull 's fork. will fix now

**Comment by JSJBDEV** [comment]
yup, looks like it was a really dumb mistake, should have an update in like an hour, sorry about the wait

**Comment by JSJBDEV** [comment]
https://modrinth.com/mod/almanac-for-spyglass-astronomy/version/0.6.0

**Comment by Liamgrayskull** [comment]
Ah, thank you so much! If it's not too much trouble, could you explain the fix? I'm relatively new at modding and didn't know where I could change the environment parameters, otherwise I would've made a PR

**Comment by JSJBDEV** [comment]
> Ah, thank you so much! If it's not too much trouble, could you explain the fix? I'm relatively new at modding and didn't know where I could change the environment parameters, otherwise I would've made a PR

Yeah, no worries! basically, I was registering my `ClientPlayNetworking.registerGlobalReceiver` in the normal ModInitializer - both the server and client see this initializer, however, the server doesn't have any of the files in Minecraft with "client" anywhere in their path so it cannot load, I then moved this to the ClientInit class witch specifically only initializes on the client, hence the server never sees it, and never needs to, in this case this is so we can move data from Spyglass (which is inherently client side only) to the server to store and thus to other players

**Comment by Liamgrayskull** [comment]
I see! That helps tons, I've had perhaps too much confusion on how mc handles server/client registries, it seems to be a really nice implementation, great work! And thank you again, this'll help me greatly!
